scrsz = get(groot,'ScreenSize');
F1 = figure('Name', 'Glc', ...
       'Position', [scrsz(1)/2 scrsz(2)/2 3*scrsz(3)/4 3*scrsz(4)/4], ...
       'Color', 'w', 'Units', 'Normalized');

axis([0, 9, 0, 9]);
Q = gca;
Q.Units = 'normalized';
Q.Position = [0.05, 0.05, 0.90, 0.90];
title('Glc Isotopomers');

hold on;

C = 'k';
FEC = 'r';
MS = 12;
SR = 0.09/MS;

IDs = {'oooooo', ...
       'xooooo', ...
       'oxoooo', ...
       'xxoooo', ...
       'ooxooo', ...
       'xoxooo', ...
       'oxxooo', ...
       'xxxooo', ...
       'oooxoo', ...
       'xooxoo', ...
       'oxoxoo', ...
       'xxoxoo', ...
       'ooxxoo', ...
       'xoxxoo', ...
       'oxxxoo', ...
       'xxxxoo', ...
       'ooooxo', ...
       'xoooxo', ...
       'oxooxo', ...
       'xxooxo', ...
       'ooxoxo', ...
       'xoxoxo', ...
       'oxxoxo', ...
       'xxxoxo', ...
       'oooxxo', ...
       'xooxxo', ...
       'oxoxxo', ...
       'xxoxxo', ...
       'ooxxxo', ...
       'xoxxxo', ...
       'oxxxxo', ...
       'xxxxxo', ...
       'ooooox', ...
       'xoooox', ...
       'oxooox', ...
       'xxooox', ...
       'ooxoox', ...
       'xoxoox', ...
       'oxxoox', ...
       'xxxoox', ...
       'oooxox', ...
       'xooxox', ...
       'oxoxox', ...
       'xxoxox', ...
       'ooxxox', ...
       'xoxxox', ...
       'oxxxox', ...
       'xxxxox', ...
       'ooooxx', ...
       'xoooxx', ...
       'oxooxx', ...
       'xxooxx', ...
       'ooxoxx', ...
       'xoxoxx', ...
       'oxxoxx', ...
       'xxxoxx', ...
       'oooxxx', ...
       'xooxxx', ...
       'oxoxxx', ...
       'xxoxxx', ...
       'ooxxxx', ...
       'xoxxxx', ...
       'oxxxxx', ...
       'xxxxxx'};

xc = 1.0;
yc = 8.0;

for i = 1:64
    ID = char(IDs(i));
    FE = XO2FE(ID);
    Draw6Carbons(xc, yc, C, FE, FEC, MS, SR, ID, 'B');
    xc = xc + 1.0;
    if xc > 8.0
        yc = yc - 1.0;
        xc = 1.0;
    end
end

axis off;
dummy = 1;

